version: '3.8'
services:
  dev-db:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postrgesql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nest-expenses-api

volumes:
  postgres-data:
