version: '3.8'
services:
  dev-db:
    image: postgres:15.1-alpine
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postrgesql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nest-expenses-api
  redis:
    image: redis:7
    ports:
      - 6379:6379
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081

volumes:
  postgres-data:
